apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: logstash
  namespace: logging
spec:
  selector:
    matchLabels:
      component: logstash
      provider: openshift
  template:
    metadata:
      creationTimestamp: null
      labels:
        component: logstash
        logging-infra: fluentd
        provider: openshift
      name: fluentd-logstash
    spec:
      containers:
      - name: fluentd-logstash
        image: docker.io/logstash:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9400
        command:
        - "/usr/share/logstash/bin/logstash"
        - "-e"
        - "input { tcp { port => 9400 codec => fluent } } output { stdout { codec => rubydebug } }"
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 512Mi
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      nodeSelector:
        logging-infra-fluentd: "true"
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: aggregated-logging-fluentd
      serviceAccountName: aggregated-logging-fluentd
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
