---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: logstash
  namespace: logging
  labels:
    component: logstash
spec:
  replicas: 1
  template:
      metadata:
        labels:
          component: logstash
      spec:
        containers:
        - name: fluentd-logstash
          image: docker.io/logstash:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 9400
          command:
          - "/usr/share/logstash/bin/logstash"
          - "-e"
          - "input { tcp { port => 9400 codec => fluent } } output { stdout { codec => rubydebug } }"
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 512Mi
          volumeMounts:
          - mountPath: /usr/share/logstash/data
            name: data
        nodeSelector:
          logging-infra-fluentd: "true"
        restartPolicy: Always
        volumes:
        - name: data
        emptyDir: {}
--- 
apiVersion: v1
kind: Service
metadata:
  labels:
    logging-infra: support
  name: logstash
  namespace: logging
spec:
  ports:
    - name: logstash-forward
      port: 9400
      protocol: TCP
      targetPort: 9400
  selector:
    component: logstash

